### ISSUE TITLE
How to export css with library?

### ISSUE THREAD

**Issue by sthomp** [prograhammer/vue-library-template#2]
Hi there,

Im using your template to create a components library. As part of my library I'd like to have a `colors.css` file that consumers of the library can use. For example:

colors.css:
```
:root {
  --my-color-red: #F23C57;
  --my-color-gray: #34495e;
}
```

Then when I consume the library I could do something like:
```
import 'my-library.css'
import Hello from 'my-library'

<div style='color:var(--my-color-red))'>Hello World</div>
<hello></hello>
````

Any suggestions to do this? 

Thanks!

**Comment by prograhammer** [comment]
Oh yeah, that's easy. Just do `@import "~my-library/dist/lib/my-library.css"` in your main.js or main.scss file of the project using your library.

Explanation: When you run `npm run build:lib` it will put both a .js and .css (if you have styles) into the **dist/lib** folder of your library. Use the tilde `~` to reference **node_modules** folder from the project that wants the css from your library.
