### ISSUE TITLE
Something is wrong with camelizer

### ISSUE THREAD

**Issue by razbakov** [prograhammer/vue-library-template#3]
I ran `vue init prograhammer/vue-library-template`
Name: `prograhammer_vue-library-template`
Than I ran `npm run dev`
I got failure:

```
 import prograhammer_vue-library-template from './components/hello';
```

**Comment by prograhammer** [comment]
Give it a simplier name, like `razba` or something, for a work-a-round. It's trying to camelize the dashes or underscores and had a problem. Let me check to see exactly why it's not accepting those types of characters (and I may need to enclose some areas in the template in quotes)...

**Comment by prograhammer** [comment]
Fixed. So now you can use names for your library like `foo_bar-baz`. Thanks for reporting this issue!

**Comment by razbakov** [comment]
Thanks for fixing!

**Comment by razbakov** [comment]
Btw, do you know why we need all the build tools in each component repository? Why not to use docker container with all the tools?

**Comment by prograhammer** [comment]
I've yet to deep dive into Docker, but my guess is that keeping all the build tools is helpful for mainly public open source repos and a wider audience target. Folks can have everything they need to build and also contribute without the need for Docker. That's an interesting approach though, you have a good article for me to read on that? Thank for the heads up. :-)
